MysteryGame: main.cpp
	g++ -O3 main.cpp -g -o MysteryGame -lGLEW -lglfw -lGL -lX11 -lpthread -lXrandr -lstdc++fs -lassimp -ldl -lXxf86vm -lXinerama -lXcursor -lSOIL -lrt -lm -std=c++11

clean:
	rm MysteryGame
